### ISSUE TITLE
Inline image support in ProtonMail with regard to other PGP softwares

### ISSUE THREAD

**Issue by nguyenkims** [ProtonMail/WebClients#253]
Hi

It seems that ProtonMail web ui doesn't handle inline image in PGP encrypted email sent by other PGP softwares. When an email is embedded inline, I also need to refresh the web page in order for the image to be shown as an attachment.

![2021-09-15 at 17 41](https://user-images.githubusercontent.com/3167780/133465398-03582676-6cc9-4146-8281-a42fc5e0c4f6.png)

This is how the email looks like in other PGP softwares
![2021-09-15 at 17 43](https://user-images.githubusercontent.com/3167780/133465591-f8e05f97-66ef-4554-a884-c4a6c088f332.png)

I've done some tests and:
- The inline image problem doesn't happen with unencrypted email.
- Inline images created by ProtonMail composer seem to be correctly handled by other PGP softwares.
- Inline images created by ProtonMail composer works well when emails are between ProtonMail accounts

I have tested with the following PGP softwares:
- GPGTools
- Thunderbird
- Canary Mail
- FlowCrypt

As this is rather a software bug and not related to my account, I create a GitHub issue instead of using the "reporting bug" inside ProtonMail web app.
 
Please complete the following checklist (by adding [x]):
- [X ] I have searched open and closed issues for duplicates
- [ X] This isn't a feature request
- [ X] This is not a report about my app not working as expected

----------------------------------------

**Comment by Swiip** [comment]
Thanks for reporting. It's indeed a regression on our side. We will fix it in the upcoming updates.

**Comment by nguyenkims** [comment]
@Swiip thanks! Do you know when the update will be released?

**Comment by nox-x** [comment]
@Swiip JFYI: I made the same observations as @nguyenkims.
In addition: it also affects attachments using inline-PGP or PGP/MIME methods for encryption. And so it seems not to be an "exclusive" inline-pgp bug.

**Comment by purple-emily** [comment]
Attachments do not show if the email and attachment was encrypted using PGP externally (simplelogin). If I turn the encryption off, then resend the email, all the attachments show.

**Comment by Wilco-One** [comment]
> Attachments do not show if the email and attachment was encrypted using PGP externally (simplelogin). If I turn the encryption off, then resend the email, all the attachments show.

Is this issue already fixed?

**Comment by nguyenkims** [comment]
@Swiip hey do you know if this issue is already fixed?

**Comment by ESMP** [comment]
Still having this issue, no attachments show when sent via SimpleLogin with PGP enabled.

**Comment by Swiip** [comment]
Hey, I'm very sorry to not monitor GitHub much. The fix I was referring before is out for a long time now (oct 2021). This issue should be fixed.

And indeed, testing today, receiving a pgp email with embedded images seems ok to us. We also have tested through Simple Login without any issues.

@ESMP If you still experience issue can you try sending one example of failing email to me or exporting one in .eml and send it to me?

**Comment by ESMP** [comment]
Hi @Swiip ! Thank you for your quick reply. It's very strange in fact. If I export the email as .eml or open it using MailMate via ProtonMail Bridge, the attachment does show and I can download it. However, when using the web or iOS clients, the email appears to be text only and there appears to be no attachment. Which puts my mind at ease because I thought the attachments were lost.

**Comment by Swiip** [comment]
Your mail looks in a very specific format. PGP emails are pure text and attachments are inlined in the mail body. Yet it should be detected by our clients. There is something definitely odd.

If you have any way to send that kind of message to me, I should be able to know more.
